# Numpy Mathematical Calculator

## Objective:

To build a Python-based calculator using the **NumPy** library that performs:

- Basic arithmetic operations
- Statistical analysis
- Array manipulation

This project helps students understand how NumPy is used in real-world numerical computing tasks.

---

## Key Features:

### 1. Basic Arithmetic Operations

- Addition, Subtraction, Multiplication, Division
- Power operations between two arrays

### 2. Statistical Operations

- Mean, Median, Standard Deviation, Variance
- Minimum, Maximum, Sum, Product
- Shape, Size, and Data Type

### 3. Array Manipulation

- Reshaping arrays (when possible)
- Sorting and Reverse Sorting
- Unique value extraction
- Accessing first and last elements
- Filtering values greater than the mean

In [2]:
import numpy as np

In [19]:
print("Basic Arithmetic Operation")
print("-------------------------------")
a=input("enter the ele with space")
arr1=np.array([int(i) for i in a.split()])
b=input("enter the ele with space")
arr2=np.array([int(i) for i in b.split()])
print(arr1)
print(arr2)
print(f"addition       :{arr1+arr2}")
print(f"subtraction    :{arr1-arr2}")
print(f"multiplication : {arr1*arr2}")
print(f"division       : {arr1/arr2}")
print(f"floor division :{arr1//arr2}")
print(f"modulus division:{arr1%arr2}")
print(f"exponensial     :{arr1**arr2}")

Basic Arithmetic Operation
-------------------------------
enter the ele with space2 3 4 5
enter the ele with space6 7 8 9
[2 3 4 5]
[6 7 8 9]
addition       :[ 8 10 12 14]
subtraction    :[-4 -4 -4 -4]
multiplication : [12 21 32 45]
division       : [0.33333333 0.42857143 0.5        0.55555556]
floor division :[0 0 0 0]
modulus division:[2 3 4 5]
exponensial     :[     64    2187   65536 1953125]


In [22]:
print("Statistical Operations")
print("---------------------------")
n=input("enter the elements with space")
s=np.array([int(i) for i in n.split()])
print(s)
print(f" mean             :{np.mean(s)}")
print(f"median            :{np.median(s)}")
print(f"standard devation : {np.std(s)}")
print(f"variance          :{np.var(s)}")
print(f"minimum value     :{np.min(s)}")
print(f"maximum value     :{np.max(s)}")
print(f"sum               :{np.sum(s)}")
print(f"product           :{np.prod(s)}")
print(f"shape    : {s.shape}")
print(f"size     : {s.size}")
print(f"data type: {s.dtype}")

Statistical Operations
---------------------------
enter the elements with space7 65 34 42 8
[ 7 65 34 42  8]
 mean             :31.2
median            :34.0
standard devation : 21.866869917754578
variance          :478.16
minimum value     :7
maximum value     :65
sum               :156
product           :5197920
shape    : (5,)
size     : 5
data type: int64


In [23]:
print("Array Manipulation")
print("-----------------------")

n=input("enter the ele with space")
arr=np.array([int(i) for i in  n.split()])
print(arr)
resh=int(input("enter the reshaping array 1 2 or 3"))
if resh==2 or 1:
  row=int(input("enter rowsize"))
  col=int(input("enter colsize"))
  print(f"reshaping : {arr.reshape(row,col)}")
else:
  row=int(input("enter rowsize"))
  col=int(input("enter colsize"))
  ele=int(input("enter elesize"))
  print(f"reshaping : {arr.reshape(row,col,ele)}")
st=np.sort(arr)
print(f"sorting {st}")
f=np.flip(st)
print(f"reverse sorting {f}")
print(f"unique {np.unique(arr)}")
print(f"first {arr[0]}")
print(f"last {arr[-1]}")




Array Manipulation
-----------------------
enter the ele with space23 4 56 43 17 7 8 98
[23  4 56 43 17  7  8 98]
enter the reshaping array 1 2 or 32
enter rowsize4
enter colsize2
reshaping : [[23  4]
 [56 43]
 [17  7]
 [ 8 98]]
sorting [ 4  7  8 17 23 43 56 98]
reverse sorting [98 56 43 23 17  8  7  4]
unique [ 4  7  8 17 23 43 56 98]
first 23
last 98
