In [32]:
import  numpy as np

In [33]:
import numpy as np

# Create arrays for students and subjects
students = np.array(["Alice", "Bob", "Charlie", "David", "Eva"])
subjects = np.array(["Math", "Science", "English", "History", "Computer"])

marks = np.array([
    [85, 78, 92, 74, 88],
    [79, 82, 84, 80, 76],
    [91, 89, 95, 90, 92],
    [72, 75, 70, 68, 74],
    [88, 90, 85, 86, 87]
])

print("Marks Array:\n", marks)


Marks Array:
 [[85 78 92 74 88]
 [79 82 84 80 76]
 [91 89 95 90 92]
 [72 75 70 68 74]
 [88 90 85 86 87]]


In [34]:
print("Array Properties:")
print("Shape:", marks.shape)
print("Dimensions:", marks.ndim)
print("Size:", marks.size)
print("Data Type:", marks.dtype)
print("Number of Students:", len(students))
print("Number of Subjects:", len(subjects))


Array Properties:
Shape: (5, 5)
Dimensions: 2
Size: 25
Data Type: int32
Number of Students: 5
Number of Subjects: 5


In [35]:

flat_marks = marks.flatten()
print("Flattened Marks:", flat_marks)


reshaped_marks = marks.T
print("\nReshaped Marks (Subjects × Students):\n", reshaped_marks)


Flattened Marks: [85 78 92 74 88 79 82 84 80 76 91 89 95 90 92 72 75 70 68 74 88 90 85 86
 87]

Reshaped Marks (Subjects × Students):
 [[85 79 91 72 88]
 [78 82 89 75 90]
 [92 84 95 70 85]
 [74 80 90 68 86]
 [88 76 92 74 87]]


In [24]:
new_student = np.array([[80, 85, 78, 82, 88]])  # 5 marks
marks = np.vstack([marks, new_student])
students = np.append(students, "Frank")

print("After adding new student:\n", marks)
print("Updated Students:", students)


After adding new student:
 [[85 78 92 74 88]
 [79 82 84 80 76]
 [91 89 95 90 92]
 [72 75 70 68 74]
 [88 90 85 86 87]
 [80 85 78 82 88]]
Updated Students: ['Alice' 'Bob' 'Charlie' 'David' 'Eva' 'Frank']


In [ ]:
new_subject_marks = np.array([[89], [75], [94], [70], [90], [88]])  
marks = np.hstack([marks, new_subject_marks])
subjects = np.append(subjects, "Art")

print("\n Subject added successfully!")
print("New Marks Shape:", marks.shape)
print("Subjects:", subjects)

In [37]:

marks[:, subjects == "Computer"] += 5

remove_index = np.where(students == "Bob")[0][0]
marks = np.delete(marks, remove_index, axis=0)
students = np.delete(students, remove_index)


unique_marks = np.unique(marks)

print("After Modification:\n", marks)
print("Updated Students:", students)
print("Unique Marks:", unique_marks)


After Modification:
 [[85 78 92 74 93]
 [91 89 95 90 97]
 [72 75 70 68 79]
 [88 90 85 86 92]]
Updated Students: ['Alice' 'Charlie' 'David' 'Eva']
Unique Marks: [68 70 72 74 75 78 79 85 86 88 89 90 91 92 93 95 97]


In [27]:
print("Original Data Type:", marks.dtype)


marks_float = marks.astype(float)
print("Converted Data Type:", marks_float.dtype)


Original Data Type: int32
Converted Data Type: float64


In [38]:

marks_copy = marks.copy()
marks_copy[0, 0] = 100
print("Copy Example:")
print("Original Marks[0,0]:", marks[0, 0])  
print("Copied Marks[0,0]:", marks_copy[0, 0])  


marks_view = marks.view()
marks_view[0, 1] = 99
print("\nView Example:")
print("Original Marks[0,1]:", marks[0, 1])  
print("Viewed Marks[0,1]:", marks_view[0, 1])


Copy Example:
Original Marks[0,0]: 85
Copied Marks[0,0]: 100

View Example:
Original Marks[0,1]: 99
Viewed Marks[0,1]: 99


In [39]:
print("Final Marks Table:\n", marks)
print("\nStudents:", students)
print("Subjects:", subjects)
print("Final Shape:", marks.shape)


Final Marks Table:
 [[85 99 92 74 93]
 [91 89 95 90 97]
 [72 75 70 68 79]
 [88 90 85 86 92]]

Students: ['Alice' 'Charlie' 'David' 'Eva']
Subjects: ['Math' 'Science' 'English' 'History' 'Computer']
Final Shape: (4, 5)
